### ISSUE TITLE
recording not available on the device 

### ISSUE THREAD

**Issue by adeshpandey** [yutasuzuki/react-native-record-screen#12]
Hi @yutasuzuki 
I got this package work on android and sometimes on iOS too but most of the time recording is not available on the device. I am not good at iOS development hence I need your help why the recording does not save the file (I don't see any error in the xcode)

**Comment by yutasuzuki** [comment]
@adeshpandey 
Sorry. I'm not sure if there are any errors, but please check the following

1. Did you try [example](https://github.com/yutasuzuki/react-native-record-screen/tree/master/example) in this library? 
2. Did you write permissions to info.pilot and AndroidManifest.xml?
[installation](https://github.com/yutasuzuki/react-native-record-screen#installation)

**Comment by adeshpandey** [comment]
@yutasuzuki Example app is working fine but I wanted to save the recordings on the device, seems the recordings are not saved properly.

**Comment by MWaqasHussain-dev** [comment]
@adeshpandey  can you share me the code because i am having this error which i am not able to understand ?


[Unhandled promise rejection: TypeError: _reactNativeRecordScreen.default.stopRecording is not a function. (In '_reactNativeRecordScreen.default.stopRecording()', '_reactNativeRecordScreen.default.stopRecording' is undefined)]
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:293:29 in invoke
- node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
- node_modules/regenerator-runtime/runtime.js:154:27 in invoke
- node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
- node_modules/react-native/node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
- node_modules/react-native/node_modules/promise/setimmediate/core.js:200:22 in doResolve
- node_modules/react-native/node_modules/promise/setimmediate/core.js:66:11 in Promise
- node_modules/regenerator-runtime/runtime.js:188:15 in callInvokeWithMethodAndArg
- node_modules/regenerator-runtime/runtime.js:211:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:238:8 in exports.async
- node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js:212:10 in onPress
- node_modules/react-native/Libraries/Pressability/Pressability.js:691:17 in _performTransitionSideEffects
- node_modules/react-native/Libraries/Pressability/Pressability.js:628:6 in _receiveSignal
- node_modules/react-native/Libraries/Pressability/Pressability.js:524:8 in responderEventHandlers.onResponderRelease
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:265:4 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:476:2 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:500:2 in invokeGuardedCallbackAndCatchFirstError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:597:41 in executeDispatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:621:19 in executeDispatchesInOrder
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2521:28 in executeDispatchesAndRelease
* [native code]:null in forEach
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:836:4 in forEachAccumulated
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2546:20 in runEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2702:18 in runExtractedPluginEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2639:35 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17712:13 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2492:29 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2638:16 in _receiveRootNodeIDEvent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2767:27 in receiveTouches
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:416:4 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by MWaqasHussain-dev** [comment]
i have downloaded the project added the info pilot and permission also installed  pod  but when i run it it gives me this

**Comment by MWaqasHussain-dev** [comment]
import React, { useState, useMemo, useCallback } from 'react';
import {
  StyleSheet,
  View,
  Text,
  Dimensions,
  StatusBar,
  SafeAreaView,
  ScrollView,
  TouchableHighlight,
  Button,
} from 'react-native';

import RecordScreen from 'react-native-record-screen';
import Video from 'react-native-video'
export default function App() {
  const [uri, setUri] = useState('');
  const [recording, setRecording] = useState(false);

  const _handleOnRecording = async () => {
    if (recording) {
      setRecording(false);
      const res = await RecordScreen.stopRecording().catch((error) =>
        console.warn(error)
      );
      console.log('res', res);
      if (res) {
        setUri(res.result.outputURL);
      }
    } else {
      setUri('');
      setRecording(true);
      await RecordScreen.startRecording().catch((error) => {
        console.warn(error);
        setRecording(false);
        setUri('');
      });
    }
  };

  const _handleOnCleanSandbox = useCallback(() => {
    RecordScreen.clean();
  }, []);

  const btnStyle = useMemo(() => {
    return recording ? styles.btnActive : styles.btnDefault;
  }, [recording]);
 

return (
<View style={styles.btnContainer}>
        <TouchableHighlight onPress={_handleOnRecording}>
          <View style={styles.btnWrapper}>
            <View style={btnStyle} />
          </View>
        </TouchableHighlight>
      </View>
      {uri ? (
        <View style={styles.preview}>
          <Video
            source={{
              uri,
            }}
            style={styles.video}
          />
        </View>
      ) : null}
)

**Comment by yutasuzuki** [comment]
@adeshpandey "Example app is working fine" you said means it's probably saved.
If you want to save it to the camera roll, you need to save it separately since the storage location is the app's storage.
[react-native-cameraroll](https://github.com/react-native-cameraroll/react-native-cameraroll)

**Comment by MWaqasHussain-dev** [comment]
@yutasuzuki  can you please help me out its not working when i run it ?

**Comment by yutasuzuki** [comment]
@MWaqasHussain-dev 
I don't know the cause of this error, but if you look at the code, there is no React fragment.
https://reactjs.org/docs/fragments.html

Are you able to startRecording?

**Comment by MWaqasHussain-dev** [comment]
@yutasuzuki  when i click on the record button this error shows up, ? i tried googling it but nothing works out

**Comment by yutasuzuki** [comment]
@MWaqasHussain-dev Did you do a `pod install`?
https://github.com/yutasuzuki/react-native-record-screen#installation

**Comment by MWaqasHussain-dev** [comment]
@yutasuzuki  yes i did it

**Comment by adeshpandey** [comment]
@yutasuzuki seems sometimes its saving but most of the times not saving. In my app video call is going on is't that problem ?

**Comment by adeshpandey** [comment]
Hi @yutasuzuki I figured it out that since mic is used in the ongoing video/audio  call so screenrecording does not work with mic. works perfectly fine without mic permission.

**Comment by ngocthien0507anttech** [comment]
> Hi @yutasuzuki I figured it out that since mic is used in the ongoing video/audio call so screenrecording does not work with mic. works perfectly fine without mic permission.

Hi, but if I set the mic config to 'false' i can't record the audio :( do you know how to resolve it?
